# Generated by Django 4.2.4 on 2023-09-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), # NOQA E501
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Статус')), # NOQA  E501
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')), # NOQA E501
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')), # NOQA E501
            ],
            options={
                'verbose_name': 'Метка',
                'verbose_name_plural': 'Метки',
                'ordering': ['id'],
            },
        ),
    ]
